name: meg_preproc
dependencies:
  - python=3.13.1
  - numpy=2.2.0
  - scipy=1.14.1
  - matplotlib=3.10.0
  - mne=1.9.0
  - mne-bids=0.16.0
  - find-delay=2.14
  - scikit-learn=1.6.0
  - pyvistaqt=0.11.1
  - ipyevents=2.0.2
  - ipykernel=6.29.5
  - ipywidgets=8.1.5
  - darkdetect=0.8.0
  - nibabel=5.3.2
  - trame=3.7.1
  - trame-vtk=2.8.12
  - trame-vuetify=2.7.2
  - pyqt5=5.15.11
  - eelbrain=0.40
  - moviepy=2.1.1
  - gammatone=1.0.3
  - pip:
    - git+https://github.com/christianbrodbeck/TRF-Tools/archive/main.zip