name: meg_preproc
dependencies:
  - pip
  - numpy
  - scipy
  - matplotlib
  - mne
  - mne-bids
  - mne-qt-browser
  - python-picard
  - find-delay
  - scikit-learn
  - pyvistaqt
  - ipykernel
  - ipywidgets
  - darkdetect
  - ipyevents
  - nibabel
  - trame
  - trame-vtk
  - trame-vuetify
  - pyqt5
  - eelbrain
  - moviepy
  - gammatone
  - pip:
    - git+https://github.com/christianbrodbeck/TRF-Tools/archive/main.zip